export const terms = `
Terms of Service

1. Use of the Services
To use the Services provided by Smoothly Protocol LLC (“Smoothly” or “Smoothly Protocol”), you must legally be able to enter into the Agreement. By using the Services, you represent and warrant that you meet these eligibility requirements. If you do not meet these requirements, you must not access or use the Site or the Services.
Smoothly Protocol is not offered to persons or entities who reside in, are citizens of, are located in, are incorporated in, or have a registered office in jurisdictions where such services are prohibited or restricted by law. Use of a Virtual Private Network ("VPN") to circumvent these restrictions is strictly prohibited.
ARBITRATION NOTICE: These Terms contain an arbitration clause. Except for certain types of disputes mentioned in this arbitration clause, you and we agree that disputes relating to the Services will be resolved by mandatory binding arbitration, and you waive any right to a trial by jury or to participate in a class-action lawsuit or class-wide arbitration.
You are entering into a binding Agreement. By accessing or using our Services, which include our various websites, applications, and any other services that link to these Terms, as well as any information, text, links, graphics, photos, audio, video, or other materials stored, retrieved, or appearing thereon (collectively, the “Services”), you are entering into a binding agreement with us that includes these Terms and Smoothly Protocol's Privacy Policy, along with other policies referenced herein (collectively, the “Agreement”).
If there is a conflict between these Terms and any applicable additional terms, these Terms will control unless expressly stated otherwise. If you do not agree with these Terms, you may not use the Services and should not visit the Site or otherwise engage with the Services. We may update the Services, the Agreement, and any part of the Terms at any time, for any reason, at our sole discretion. Once updated, you will be bound by the Terms if you continue to use the Services. We may modify or discontinue all or part of the Services at any time and without liability to you. You should review the Terms periodically to ensure that you understand the terms and conditions that apply to your access and use of the Site.


2. Assumption of Risk
You assume the risks of engaging in transactions that rely on blockchain technology, smart contracts, and oracle software. Transactions on the Smoothly Protocol rely on smart contracts stored on the Ethereum blockchain and are dependent on data provided by decentralized oracle software. These technologies are experimental, inherently risky, and subject to change. Among other risks, bugs, malfunctions in smart contracts or oracle software, cyberattacks, or changes to the Ethereum blockchain (e.g., forks) could disrupt the protocol and even result in a total loss of digital assets or their market value.
You are solely responsible for the safekeeping of the private key associated with the blockchain address used to interact with the Smoothly Protocol. We assume no liability or responsibility for any such risks. If you are not comfortable assuming these risks, you should not access or engage in transactions using blockchain-based technology.
Blockchain technology's immutable nature means entries generally cannot be deleted or modified. This includes smart contracts and digital assets generated by them. Thus, transactions recorded on the blockchain, including transfers of digital assets and data programmed into these assets, are permanent and cannot be undone by us or anyone else.
You must be cautious when finalizing transactions recorded on the blockchain. We are not liable for any third-party services or links. We are not responsible for the content or services of any third-party, including, without limitation, any applications or self custodial wallets like MetaMask, and we make no representations regarding the content or accuracy of any third-party services or materials.
You acknowledge and agree that all transactions accessed through the Services will be automatically processed using blockchain-based smart contracts and reliant on the integrity and accuracy of oracle software data. By engaging in transactions using the Services, you acknowledge and consent to the automatic processing of all transactions in connection with using the Services.
You bear sole responsibility for evaluating the Services before using them, and all transactions accessed through the Services are irreversible, final, and without refunds. The Services may be disabled, disrupted, or adversely impacted due to various factors, including cyber-attacks, surges in activity, computer viruses, or other operational or technical challenges, including those associated with the oracle software. We disclaim any ongoing obligation to notify you of all of the potential risks of using and accessing our Services.
You acknowledge there is a real risk that assets deposited into the Smoothly Protocol may suffer complete and permanent economic loss should the protocol’s technical or economic mechanisms, including the oracle software, suffer catastrophic failure. You acknowledge that the terms of the Smoothly Protocol may change at any time for any reason, including but not limited to protocol fees, rewards, accessibility, and changes in oracle software operations. You agree to accept these risks and agree that you will not seek to hold any Smoothly Protocol Indemnified Party responsible for any consequent losses.


3. Privacy
Smoothly Protocol values your privacy. While we implement various measures to safeguard the integrity and security of your data, it is essential to understand the inherent risks associated with digital transactions and data storage.
Your interaction with the Smoothly Protocol, including the use of blockchain technology, inherently makes certain information publicly available. This includes but is not limited to transaction data and wallet addresses. As the Ethereum blockchain is public and decentralized, your transactions are visible to anyone. We have no control over, nor do we have the ability to alter, blockchain data once transactions are executed.
Although we do not collect personal identifying information (PII) directly through the Smoothly Protocol, it is crucial to recognize that your blockchain address and the associated transactions are permanently recorded on the Ethereum blockchain and publicly visible. We encourage you to exercise caution in revealing any additional personal information related to your blockchain address.
We comply with all valid subpoena requests concerning any data or information we may hold or have access to. By accessing and using the Smoothly Protocol, you understand and consent to our collection, use, and potential disclosure of data and information related to your blockchain transactions as dictated by law.
Please be aware that our website and services may contain links to third-party websites or services, which are not operated or controlled by us. This Privacy section does not apply to third-party websites or services; we encourage you to review the privacy policies of any third-party websites or services before providing them with your personal information.
In the event of a data breach or other unauthorized access to our systems, we will take reasonable steps to mitigate the breach's effects and will comply with all applicable laws regarding such a breach. However, given the nature of our services and the public availability of blockchain data, our ability to control or mitigate the exposure of data on the Ethereum blockchain is inherently limited.


  4. Taxes
As a user of the Smoothly Protocol, you bear sole responsibility for determining and fulfilling the tax obligations that arise from your use of our services, including engaging in transactions with the protocol. This encompasses any taxes, duties, or assessments levied by governmental authorities in relation to the crypto assets or rewards you accrue, hold, transfer, or otherwise interact with via the Smoothly Protocol.
Blockchain-based transactions, including those facilitated by the Smoothly Protocol, are a novel area in many jurisdictions and their tax treatment may be unclear or subject to change. It is essential for you to understand that participation in blockchain activities, such as staking and pooling rewards, could have tax implications. We strongly advise you to consult with a qualified tax professional to ensure compliance with your local tax laws and regulations.
Smoothly Protocol does not provide tax advice, nor do we have any responsibility to advise you on the tax implications of any transactions conducted through our protocol. Our platform does not monitor, report, or withhold any taxes on your behalf. As a result, you must report and remit the appropriate taxes to the relevant tax authorities.
Please be aware that your failure to comply with your local tax laws and regulations could result in penalties, fines, or other legal consequences. By using the Smoothly Protocol, you acknowledge and agree that you are solely responsible for keeping informed about, and compliant with, tax laws and regulations that apply to your transactions.


5. Prohibited Content
In using the Smoothly Protocol, you are required to comply with all applicable laws, rules, and regulations, as well as the terms of this Agreement. The following activities are strictly prohibited:

A. Illegal Activities: Using the Smoothly Protocol for, or to facilitate, any illegal activities, including but not limited to money laundering, terrorism financing, tax evasion, or trading in illegal substances or goods.

B. Unauthorized Commercial Use: Exploiting the Smoothly Protocol for any commercial purposes not expressly authorized by us.

C. Malicious Code: Uploading, transmitting, or activating viruses, worms, Trojan horses, time bombs, or any other type of malicious software that might harm the protocol, other users, or any associated networks or services.

D. Unauthorized Access and Interference: Attempting to gain unauthorized access to the Smoothly Protocol or its related systems and networks, or interfering with their normal operation. This includes hacking, denial-of-service attacks, and any other form of cyber attacks or unauthorized exploitation.

E. False Pretenses: Using the services under false or fraudulent pretenses, including providing incorrect or misleading information.

F. Interference with Other Users: Interfering with, or disrupting, other users' access or usage of the Smoothly Protocol.

G. Violation of Third Party Rights: Violating the rights of any third party, including intellectual property, privacy, or publicity rights.

H. Deceitful Behavior: Engaging in any form of deceitful behavior in your use of the Protocol.

I. Anticompetitive Conduct: Participating in any activity that is deemed anticompetitive or otherwise in violation of applicable competition laws.


Violation of these rules may lead to actions on our part, including but not limited to restricting or terminating your access to the Smoothly Protocol. We reserve the right to take appropriate measures, including legal action, in the case of serious or repeated violations.


6. Disclaimers and Limitations of Liability
No Representations or Warranties: THE SERVICES OF SMOOTHLY PROTOCOL ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. THE SMOOTHLY PROTOCOL, including but not limited to, its parent company, subsidiaries, affiliates, related companies, officers, directors, contractors, employees, agents, representatives, partners, and licensors associated with the Smoothly Protocol (collectively “SMOOTHLY PROTOCOL INDEMNIFIED PARTIES”) DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM SMOOTHLY PROTOCOL INDEMNIFIED PARTIES OR THROUGH THE SERVICES, WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN.
Risks Associated with Blockchain and Smart Contracts: Transactions on the Smoothly Protocol involve blockchain technology and smart contracts, which are experimental and carry inherent risks. These include, but are not limited to, technical malfunctions, cyberattacks, changes to blockchain networks, and potential total loss of cryptoassets or funds. Transactions are irreversible, and THE SMOOTHLY PROTOCOL INDEMNIFIED PARTIES CANNOT ALTER OR REVERSE TRANSACTIONS ON THE BLOCKCHAIN.
Third-Party Risks: The Smoothly Protocol is not responsible for any third-party services, applications, or websites linked to or from our services. Your interaction with third-party products or services is solely at your own risk.

Limitation of Liability: TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SMOOTHLY PROTOCOL INDEMNIFIED PARTIES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOOD-WILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO, USE OF, OR INABILITY TO ACCESS OR USE THE SERVICES; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES; (C) ANY CONTENT OBTAINED FROM THE SERVICES; OR (D) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSACTIONS OR CONTENT.

User Responsibility: You are solely responsible for securing your wallet and private key. SMOOTHLY PROTOCOL INDEMNIFIED PARTIES are not responsible for losses due to unauthorized access or failure to secure your wallet.
Jurisdictional Limitations: Some jurisdictions do not permit certain disclaimers or limitations of liability. In these jurisdictions, the exclusions and limitations will apply to the greatest extent enforced under applicable law.

Total Liability Cap: THE AGGREGATE LIABILITY OF THE SMOOTHLY PROTOCOL INDEMNIFIED PARTIES ARISING OUT OF OR RELATING TO THE USE OF OR INABILITY TO USE THE SERVICES SHALL NOT EXCEED THE AMOUNT YOU HAVE PAID TO SMOOTHLY PROTOCOL FOR THE SERVICES IN THE SIX MONTHS PRIOR TO THE EVENT GIVING RISE TO THE LIABILITY.

Acknowledgement of Risks: You acknowledge and agree that your use of the Services is at your own risk and that the risks outlined in this section are inherent to the services provided.
Exclusion of Liability for Certain Damages: NO SMOOTHLY PROTOCOL INDEMNIFIED PARTY SHALL BE LIABLE FOR ANY DAMAGES CAUSED IN WHOLE OR IN PART BY: (A) USER ERROR, SUCH AS FORGOTTEN PASSWORDS, INCORRECTLY CONSTRUCTED SMART CONTRACTS OR OTHER TRANSACTIONS; (B) SERVER FAILURE OR DATA LOSS; (C) MALFUNCTION, UNEXPECTED FUNCTION, OR UNINTENDED FUNCTION OF THE BLOCKCHAIN, ANY COMPUTER OR CRYPTOASSET NETWORK (INCLUDING ANY WALLET PROVIDER), INCLUDING WITHOUT LIMITATION LOSSES ASSOCIATED WITH NETWORK FORKS, REPLAY ATTACKS, DOUBLE-SPEND ATTACKS, SYBIL ATTACKS, 51% ATTACKS, GOVERNANCE DISPUTES, MINING DIFFICULTY, CHANGES IN CRYPTOGRAPHY OR CONSENSUS RULES, HACKING, OR CYBERSECURITY BREACHES; (D) ANY CHANGE IN VALUE OF ANY CRYPTOASSET; (E) ANY CHANGE IN LAW, REGULATION, OR POLICY; (F) EVENTS OF FORCE MAJEURE; OR (G) ANY THIRD PARTY.

Scope of Liability Limitations: THIS LIMITATION OF LIABILITY IS INTENDED TO APPLY WITHOUT REGARD TO WHETHER OTHER PROVISIONS OF THESE TERMS HAVE BEEN BREACHED OR HAVE PROVEN INEFFECTIVE. THE LIMITATIONS SET FORTH IN THIS SECTION SHALL APPLY REGARDLESS OF THE FORM OF ACTION, WHETHER ASSERTED LIABILITY OR DAMAGES ARE BASED ON CONTRACT, INDEMNIFICATION, TORT, STRICT LIABILITY, STATUTE, OR ANY OTHER LEGAL OR EQUITABLE THEORY, AND WHETHER OR NOT THE SMOOTHLY PROTOCOL INDEMNIFIED PARTIES HAVE BEEN INFORMED OF THE POSSIBILITY OF ANY SUCH DAMAGE.

7. Indemnification
You agree to indemnify, defend, and hold harmless the Smoothly Protocol Indemnified Parties from any claim, liability, loss, damage, cost, or expense, including reasonable attorneys’ fees, arising out of or related to your use of the Smoothly Protocol Services. This includes but is not limited to:
a) Your breach or alleged breach of the Agreement, including these Terms and any other policy or guideline applicable to the Services;

b) Any content or data you submit, post, or transmit through the Services;

c) Your misuse of the Services, including any use contrary to the intended function or purpose of the Smoothly Protocol or its smart contracts;

d) Your violation of any laws, rules, regulations, codes, statutes, ordinances, or orders of any governmental or quasi-governmental authorities;

e) Your infringement or violation of the rights of any third party, including intellectual property rights, publicity, confidentiality, property, or privacy rights;

f) Your use of any third-party product, service, and/or website accessed or used in connection with the Smoothly Protocol Services;

g) Any misrepresentation made by you in connection with your use of the Smoothly Protocol Services.
  We reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us. You agree to cooperate with our defense of such claims. You will not settle any claim without the prior written consent of the Smoothly Protocol Indemnified Parties.


8. Arbitration Agreement and Waiver of Rights, Including Class Actions
PLEASE READ THIS SECTION CAREFULLY AS IT SIGNIFICANTLY AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT AND TO HAVE A JURY HEAR YOUR CLAIMS. THIS SECTION CONTAINS PROCEDURES FOR MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.
Agreement to Resolve Disputes through Negotiation: Before commencing any legal proceeding against Smoothly Protocol, including arbitration, you and Smoothly Protocol agree to attempt to resolve any dispute, claim, or controversy arising out of or relating to this agreement or the services through good faith negotiations. This process involves providing a written notice specifying the details of the dispute. The parties will have sixty (60) days from the initial notice to try to resolve the dispute through videoconference or telephone. If unresolved within ninety (90) days, either party may proceed to arbitration.
Agreement to Arbitrate: Any unresolved disputes will be resolved through binding arbitration under the International Arbitration Rules of the International Centre for Dispute Resolution. The arbitration will take place in California, United States, and will be conducted in English. The arbitrator(s) should be experienced in Internet technology, software applications, financial transactions, and blockchain technology. The prevailing party will be entitled to reasonable attorneys' fees and costs. The arbitrator's decision will be consistent with the “Limitation of Liability” section of these Terms.


Waiver of Jury Trial and Class Actions: By using the Smoothly Protocol services, you waive the right to a trial by jury or to participate as a plaintiff or class member in any class action or representative proceeding. The arbitrator may not consolidate more than one person's claims and may not preside over any form of class or representative proceeding, unless both you and Smoothly Protocol agree otherwise in writing.
Opt-Out of Arbitration: You may opt-out of this arbitration agreement by providing written notice to Smoothly Protocol within a specified period.
Confidentiality of Arbitration: Neither party may disclose the existence, content, or results of any arbitration without the prior written consent of both parties, except as required by law.
This arbitration agreement will apply to any disputes between you and Smoothly Protocol as of the date you first accepted these Terms or accepted any subsequent changes to these Terms.


9. Waiver of Injunctive or Other Equitable Relief
TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOU AGREE THAT YOU WILL NOT BE ENTITLED TO, AND HEREBY WAIVE ANY RIGHT TO, SEEK AN INJUNCTION OR OTHER EQUITABLE RELIEF OF ANY KIND AGAINST THE SMOOTHLY PROTOCOL OR ANY SMOOTHLY PROTOCOL INDEMNIFIED PARTY. THIS INCLUDES, BUT IS NOT LIMITED TO, ANY COURT OR OTHER ACTION THAT MAY INTERFERE WITH OR PREVENT THE DEVELOPMENT, OPERATION, OR EXPLOITATION OF THE SMOOTHLY PROTOCOL SERVICES, OR ANY OTHER WEBSITE, APPLICATION, CONTENT, SUBMISSION, PRODUCT, SERVICE, OR INTELLECTUAL PROPERTY OWNED, LICENSED, USED, OR CONTROLLED BY ANY SMOOTHLY PROTOCOL INDEMNIFIED PARTY.
BY AGREEING TO THIS WAIVER, YOU UNDERSTAND AND ACKNOWLEDGE THAT YOU WILL NOT SEEK TO RESTRAIN OR OTHERWISE IMPACT THE DEVELOPMENT, DISTRIBUTION, OR OPERATION OF THE SMOOTHLY PROTOCOL SERVICES, OR RELATED PRODUCTS OR SERVICES, THROUGH LEGAL OR EQUITABLE MEANS. THIS WAIVER IS A FUNDAMENTAL PART OF THE AGREEMENT BETWEEN YOU AND SMOOTHLY PROTOCOL, AND IS INTENDED TO APPLY TO ALL FORMS OF EQUITABLE RELIEF, INCLUDING INJUNCTIONS AND SPECIFIC PERFORMANCE.


10. Termination and Cancellation
This Agreement remains effective unless and until it is terminated by either you or us. As a user, you may terminate your agreement with the Smoothly Protocol at any time by discontinuing all access to the Smoothly Protocol site, protocol, and services. Conversely, the Smoothly Protocol reserves the right, in its sole judgment, to terminate this Agreement and deny you access to its services if you fail, or are suspected of failing, to comply with any term or provision of this Agreement, including these Terms.
We also reserve the right to restrict your access to the Smoothly Protocol site or to cease providing you with all or part of the services at any time, without prior notice, particularly if we believe that:

(a) your use of the services poses a risk or liability to us,
(b) you are using the services for unlawful purposes, or
(c) it is no longer commercially viable to continue providing you with our services.

These rights are in addition to any other remedies we may have, whether in equity or at law, all of which are expressly reserved by the Smoothly Protocol. We also reserve the right to modify the services at any time, although we are under no obligation to update the services. It is your responsibility to stay informed of any changes to the services that may impact you. We may also remove the services, or any content therein, for indefinite periods or discontinue the services entirely at our discretion, without notice to you.


11. Severability
Should any provision of this Agreement, including these Terms, be found to be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from this Agreement and shall not affect the validity and enforceability of any remaining provisions. The unenforceable provision will be enforced to the fullest extent permitted by applicable law, and the remaining provisions of this Agreement will continue in full force and effect.


12. Assignment
This Agreement, including these Terms, may be assigned by us without your prior consent to any party affiliated with the Smoothly Protocol, or to its successors, in relation to any business activity associated with the Services provided by us. You are not permitted to assign or transfer any rights or obligations under this Agreement without our explicit prior written consent.


13. Entire Agreement
This Agreement, which includes these Terms and the Smoothly Protocol Privacy Policy, along with any policies or operating rules posted by us on our Services, constitutes the entire agreement and understanding between you and us. It governs your use of the Services and supersedes all prior or contemporaneous agreements, communications, and proposals, whether oral or written, between you and us. This includes any previous versions of these Terms. Our failure to exercise or enforce any right or provision of this Agreement shall not operate as a waiver of such right or provision.


14. Governing Law
These Terms, along with any separate agreements whereby we provide you Services, shall be governed by and construed in accordance with the laws of California, United States. Any disputes or interpretations of these Terms will be subject to the jurisdiction of the courts in California.
`;
